<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <article class="thisbox">
                    <div class="head">
                        <span><?php echo $this->entry->title; ?></span>
                        <span class="pull-right "><?php echo $this->entry->created; ?></span>
                    </div>
                    <div class="body">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 slide">
                                <?php foreach ($this->entry->pictures as $pic) { ?>
                                    <p class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                        <a href="<?php echo $pic['original']; ?>" class="fancybox-thumb" rel="news-<?php echo $this->entry->id; ?>" >
                                            <img class="img-thumbnail " alt=""
                                                 src="<?php echo $pic['thumb']; ?>">
                                        </a>
                                    </p>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
    <?php
    //echo $this->render('widgets/profile.phtml');
    ?>
</div>