<div class="row">
    <div class="col-lg-9 col-md-12">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <article class="thisbox">
                        <div class="head">
                            <span>&nbsp;</span>
                        </div>
                        <div class="body" style="min-height: 200px;">
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <?php foreach ($this->entry as $entry) {
                                        $gallerypath = $this->url(array(
                                                                'controller' => 'index',
                                                                'action' => 'gallery',
                                                                'id' => $entry->id
                                                            ), 'gallery');
                                        ?>
                                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                            <div class="thumbnail">
                                                <a href="<?php echo $gallerypath; ?>" class="caption">
                                                    <span class="text-muted"><?php echo $entry->title; ?></span>
                                                </a>
                                                <div class="carousel owl-carousel" data-interval="<?php echo rand(4000,12000); ?>">
                                                    <?php
                                                    $pictures = $entry->pictures;
                                                    shuffle($pictures);
                                                    array_splice($pictures,4);
                                                    foreach($pictures as $pic) { ?>
                                                    <a href="<?php echo $gallerypath; ?>">
                                                        <img class="lazyOwl" data-src="<?php echo $pic['thumb']; ?>">
                                                    </a>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
    </div>
    <div class="col-lg-3 visible-lg">
        <article class="thisbox">
            <div class="head">
                <span>Profil</span>
            </div>
            <div class="body">
                <p>
                    <img class="img-thumbnail " alt="" src="/img/profil2.jpg"/>
                </p>
                <p class="text-muted">
                    Ich fotografiere seitdem ich denken kann. Vor allem Licht, 
                    Gesichter und Momente haben mich schon immer fasziniert. 
                    Die Fotografie gibt mir die Möglichkeit dem Ausdruck zu 
                    verleihen. Aber weil man – wie Mama immer so schön sagt – 
                    auch “was anständiges lernen” soll, habe ich 2011 mein 
                    Studium der Medienwirtschaft erfolgreich abgeschlossen und 
                    war von 2008-2012 in der Formatentwicklung der 
                    TV-Produktionsfirma ITV Studios Germany tätig. Die 
                    Fotografie habe ich aber parallel nie aufgeben – sie war 
                    immer meine Nummer Eins. Seit 2011 bin ich offziell als 
                    freie Fotografin tätig. Zum Glück.
                </p>
            </div>
        </article>
    </div>
</div>
