<?php
if(isset($this->entry) && is_object($this->entry)):
?>
<div class="row">
    <div class="col-lg-12 col-md-12">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <article class="thisbox">
                        <div class="head">
                            <span>&nbsp;</span>
                        </div>
                        <div class="body">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 slide">
                                    <p class="carousel owl-carousel" data-interval="4000" data-autoheight="true">
                                        <?php
                                        $iCount = 0;
                                        foreach($this->entry->getPictures() as $pic) { 
                                            $iCount++;
                                            if($iCount > 16) break;
                                        ?>
                                            <img class="lazyOwl center-block" data-src="<?php echo $pic['original']; ?>">
                                        <?php 
                                              } ?>
                                             
                                    </p>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
    </div>

</div>
<?php
endif;