<p><a href="<?php echo $this->url(
    array(
        'controller' => 'index',
        'action'     => 'index'
    ),
    'default',
    true) ?>">Im Guestbook eintragen</a></p>
 
Guestbook Einträge: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->created) ?></dt>
    <dt><?php echo $this->escape($entry->name) ?></dt>
    <dd><?php echo $this->escape($entry->comment) ?></dd>
    <?php endforeach ?>
</dl>
