<?php
$news = $this->news;
?>
<div class="row">
    <div class="col-lg-12 col-md-12">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <article class="thisbox">
                        <div class="head">
                            <span>&nbsp;</span>
                        </div>
                        <div class="body">
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <p class="text-muted">
                                        <?php echo nl2br($news->teaser); ?>
                                    </p>
                                </div>
                                <div class="col-lg-12 col-md-12 slide">
                                    <p class="carousel owl-carousel" data-interval="4000" data-autoheight="true">
                                        <?php
                                        foreach($news->pictures as $pic) { 
                                        ?>
                                            <img class="lazyOwl center-block" data-src="<?php echo $pic['original']; ?>">
                                        <?php } ?>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
    </div>
    <?php
    /*
    <div class="col-lg-3 visible-lg">
        <article class="thisbox">
            <div class="head">
                <span>Profil</span>
            </div>
            <div class="body">
                <p>
                    <img class="img-thumbnail " alt="" src="/img/profil2.jpg"/>
                </p>
                <p class="text-muted">
                    Ich fotografiere seitdem ich denken kann. Vor allem Licht, 
                    Gesichter und Momente haben mich schon immer fasziniert. 
                    Die Fotografie gibt mir die Möglichkeit dem Ausdruck zu 
                    verleihen. Aber weil man – wie Mama immer so schön sagt – 
                    auch “was anständiges lernen” soll, habe ich 2011 mein 
                    Studium der Medienwirtschaft erfolgreich abgeschlossen und 
                    war von 2008-2012 in der Formatentwicklung der 
                    TV-Produktionsfirma ITV Studios Germany tätig. Die 
                    Fotografie habe ich aber parallel nie aufgeben – sie war 
                    immer meine Nummer Eins. Seit 2011 bin ich offziell als 
                    freie Fotografin tätig. Zum Glück.
                </p>
            </div>
        </article>
    </div>
     */
    ?>
</div>