<div class="row">
    <div class="col-lg-9 col-md-12">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <article class="thisbox">
                        <div class="head">
                            <span>Kontakt</span>
                        </div>
                        <div class="body">
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <p class="text-muted">
                                        Vielen Dank für den besuch auf meiner Website.
                                        Sie möchten gerne mehr über meine Shootings erfahren, 
                                        (oder haben andere fragen)(?) (D)dann schicken sie mir eine kurze Nachricht.
                                        (Sie erhalten kurzfristig eine Antwort von mir.) 
                                    </p>
                                    <br />
                                    <?php echo $this->partial('forms/kontakt.phtml', array('form' => $this->form));?>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
    </div>
</div>
