<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype(); ?>

<html lang="de">
	<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
       
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
					<a class="navbar-brand" href="/">Steffen Erdmann</a>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<?php 
				$options = array('ulClass' => '', 'maxDepth' => 2);
				$mainmenu = $this->navigation()->findOneByClass('nav');
				echo $this->navigation()
					->menu()
					->renderPartial(
						$this->navigation()->findOneByClass('nav'),
						array('navi.phtml', 'default')
					);
				?>
				</div>
			</nav>
		<div class="container">
			<div class="row">
	    		<?php echo $this->layout()->content;?>
		    </div>
	    </div>
	    
	    <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
		<div id="blueimp-gallery" class="blueimp-gallery">
		    <div class="slides"></div>
		    <h3 class="title"></h3>
		    <!-- The placeholder for the description label: -->
		    <p class="description"></p>
		    <a class="prev">‹</a>
		    <a class="next">›</a>
		    <a class="close">×</a>
		    <a class="play-pause"></a>
		    <ol class="indicator"></ol>
		</div>
             <div id="fb-root"></div>
             <script>(function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
	</body>
</html>
