<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype(); 
$this->headScript()->appendFile( $this->baseUrl('/js/site.js'));
?>
<html lang="de">
	<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
        <meta property="og:type"   content="website" />
        <meta property="og:title"  content="Steffen Erdmann" />
        <?php
        if(isset($this->layout()->teaser)) {
            printf('<meta property="og:description" content="%s" />', $this->layout()->teaser);
        }
        //Zend_Debug::dump();
        if(isset($this->layout()->ogPictures)) {
            foreach($this->layout()->ogPictures as $aPic) {
                printf("<meta property='og:image' content='%s' />\n", $aPic);
            }
        }
        ?>
       <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-46655871-1', 'auto');
        ga('send', 'pageview');

        </script>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
					<a class="navbar-brand" href="/">Steffen Erdmann</a>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<?php 
				$options = array('ulClass' => '', 'maxDepth' => 2);
				$mainmenu = $this->navigation()->findOneByClass('nav');
				echo $this->navigation()
					->menu()
					->renderPartial(
						$this->navigation()->findOneByClass('nav'),
						array('navi.phtml', 'default')
					);
				?>
				</div>
			</nav>
		<div class="container">
			<div class="row">
	    		<?php echo $this->layout()->content;?>
		    </div>
	    </div>
	    
	    <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
            <div id="blueimp-gallery" class="blueimp-gallery">
                <div class="slides"></div>
                <h3 class="title"></h3>
                <!-- The placeholder for the description label: -->
                <p class="description"></p>
                <a class="prev">‹</a>
                <a class="next">›</a>
                <a class="close">×</a>
                <a class="play-pause"></a>
                <ol class="indicator"></ol>
            </div>
            
            <?php
            $fm = new Zend_Controller_Action_Helper_FlashMessenger();
            $messages = array_merge($fm->getMessages(),
            $fm->getCurrentMessages());
            $fm->clearCurrentMessages();
            if(count($messages)) {
                foreach($messages as $msg) {
                    ?>
                        <div class='notifications top-right' data-message='<?php echo $msg;?>'></div>
                    <?php
                }
            }
            ?>
	</body>
</html>
