<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-xs-3 col-md-3">
                    <div  class="thumbnail">
                        <img src="/images/shop/thumb/zd0126_640x640_v1.jpg" alt="...">
                        <div class="caption">
                            <select class="form-control">
                                <?php
                                //Zend_Debug::dump($this->entry);
                                foreach ($this->entry->pictures as $pic) {
                                    printf("<option>%s</option>", basename($pic['original']));
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->