<a href="#" id="status" data-value="2">admin</a>

<table class="datatable table table-striped table-bordered">
	<thead>
		<tr>
			<th>Datum</th>
			<th>Titel</th>
			<th>Pfad</th>
			<th>Teaser</th>
		</tr>
	</thead>
	<tbody>
<?php

foreach($this->entries as $entry) {
    echo "<tr>";
    printf("<td><a href='#' class='editable text' data-name='created' data-title='Erstellungsdatum' data-type='text' data-pk='%d'>%s</a></td>",$entry->id, $entry->created);
    printf("<td><a href='#' class='editable text' data-name='title' data-title='Titel' data-type='text' data-pk='%d'>%s</a></td>",$entry->id, $entry->title);
    printf("<td><a href='#' class='editable text' data-name='path' data-title='Pfad' data-type='text' data-pk='%d'>%s</a></td>",$entry->id, $entry->path);
    printf("<td><a href='#' class='editable textarea' data-name='teaser' data-title='Teaser' data-type='text' data-pk='%d'>%s</a></td>",$entry->id, $entry->teaser);
    echo "</tr>";
}
?>
        </tbody>
</table>
