<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Erdis Gallery</title>
</head>
<body>
  <h1>Du hast eine neue Kontaktanfrage</h1>
  <h2>Absender:</h2>
  <p>
      <?php echo $this->form['name']; ?>
  </p>
    <h2>Mail:</h2>
  <p>
      <?php echo $this->form['mail']; ?>
  </p>
  <h2>Nachricht:</h2>
  <p>
      <?php echo $this->form['comment']; ?>
  </p>
</body>
</html>